### ISSUE TITLE
JS not showing the right color in the legend for a TH1F

### ISSUE THREAD

**Issue by etejedor** [dpiparo/ROOTaaS#15]
I was able to reproduce this outside of the notebook.

The problem seems to be that the generated JSON has a wrong reference in a TLegendEntry, which is referencing a TLatex object and not the TH1F.

**Comment by dpiparo** [comment]
Hi,

can you send me the lines used to create the object then streamed to json?
Two questions to be answered:
How is it streamed to xml? and to disk?

Chhers,
     Danilo

**Comment by etejedor** [comment]
I created the object with that example of the distribution of gaussian numbers.
We're working on it with Bertrand, it is some ROOT 6 issue.

**Comment by etejedor** [comment]
We're forwarding the issue to Sergey, since it looks like a bug in TBufferJSON::ConvertToJSON in ROOT 6.

**Comment by etejedor** [comment]
Sergey has fixed the bug in TBufferJSON::ConvertToJSON, now the color displays correctly in the legend.

There is still an issue: Prob <not avail> in the legend. According to Bertrand, this is a missing feature in JSRoot, not a bug.
