### ISSUE TITLE
Tab completion in C++

### ISSUE THREAD

**Issue by etejedor** [dpiparo/ROOTaaS#3]
We need to add tab completion to our cells. Useful links:

https://docs.python.org/3/library/readline.html
https://docs.python.org/3/library/rlcompleter.html

In particular, we need to define our own completer and replace the default one. The completer will use some functionality already present in ROOT to obtain a list of suggestions. There can be three cases for suggestions:
- user_word + dot + tab: get the list of methods and attributes corresponding to user_word.
  ex.  h. + tab  
- user_word + arrow + tab: analogous to the dot case.
  ex.  h-> + tab
- incomplete_user_word + tab: try to complete the incomplete_user_word
  ex.  TH + tab --- [ TH1, TH2, ... ]

**Comment by etejedor** [comment]
Another useful link with the code of the default completer:

https://hg.python.org/cpython/file/3.4/Lib/rlcompleter.py

**Comment by etejedor** [comment]
I committed a dummy completer, only to set up the mechanism of activating a new completer and deactivating it.

The completer is another extension that is loaded by toCpp(), like cpptransformer.

In cpp mode, if you type and identifier + .  and press tab twice, you should see the dummy suggestions. I haven't activated it for the magic.

**Comment by dpiparo** [comment]
Done: the completer is interfaced to TTabCom through a thin jitted layer.
